##config db 14.225.198.8
server.db.ip=localhost
server.db.port=3306
server.db.name=nro_goc
server.db.us=btoan
server.db.pw=toanhotface
server.db.maxactive=9999
login.host=103.78.0.226
login.port=8889
##config server
server.sv=1
server.port=14446
server.sv1=Nro TORA:103.78.0.226:14446:0,0,0

server.waitlogin=5
server.maxperip=1500000
server.maxplayer=15000
server.expserver=5
server.debug=false


api.port=8180
api.key=347923hfwjkhf4349982

#hikariCP
server.hikari.minIdle=5
server.hikari.poolSize=200
server.hikari.cachePre=true
server.hikari.cacheSize=250
server.hikari.cacheSqlLimit=2048

execute.command=java -jar target/nro-1-jar-with-dependencies.jar

server.event=4
## (15)
##config server 1 = halloween, 2 = 20/11 nha giao , 3 noel, 4 tet, 5 sk8/3 , 8 sk 20/11 2023
## BEEF _ TEMPLATE
## 16: trung thu
## 15 : he
## 13 : M\u00e2y tr\u00ean
## 14 : m\u00e2y d\u01b0\u1edbi
## 12 : m\u01b0a
## 11 : tuy\u1ebft
## 10 : v\u1ec7t n\u01b0\u1edbc - tr\u00ean
## 7 : l\u00e1 xanh d\u01b0\u01a1ng nh\u1ea1t - h\u00ecnh sao
## 6 : l\u00e1 v\u00e0ng 
## 5 : l\u00e1 xanh d\u01b0\u01a1ng 
## 2 : l\u00e1 xanh l\u00e1 - h\u00ecnh sao
## 1 : l\u00e1 xanh l\u00e1 